version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /opt/ha:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    depends_on:
      - traefik
    network_mode: host
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.homeassistant.rule=Host(`grafana.localhost`) && PathPrefix(`/homeassistant`)
      - traefik.http.services.homeassistant.loadbalancer.server.port=8080

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana_network
      - network1
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
      - traefik
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`) && PathPrefix(`/grafana`)
      - traefik.http.services.grafana.loadbalancer.server.port=8080


  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - grafana_network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=home_assistant
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=admin
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=admin
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.influxdb.rule=Host(`influxdb.localhost`) && PathPrefix(`/influxdb`)
      - traefik.http.services.influxdb.loadbalancer.server.port=8080
    depends_on:
      - traefik
  
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command: --api.insecure=true --providers.docker=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  grafana_network:
  network1:
    name: no-internet
    internal: true
volumes:
  grafana_data:
  influxdb_data:
