


namespace: monitoring


prometheus:
  enabled: true
  service:
    type: ClusterIP
    port: 9090
  resources: {}
  retention: "15d"
  scrapeInterval: "15s"
  scrapeTimeout: "10s"



alertmanager:
  enabled: true
  service:
    type: ClusterIP
    port: 9093
  resources: {}



pushgateway:
  enabled: true
  service:
    type: ClusterIP
    port: 9091
  resources: {}



grafana:
  enabled: true
  adminPassword: "admin" 
  service:
    type: ClusterIP
    port: 3000
  resources: {}



nodeExporter:
  enabled: true
  resources: {}



kubeStateMetrics:
  enabled: true
  resources: {}


prometheusOperator:
  enabled: true
  resources: {}


