name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzanie kodu
        uses: actions/checkout@v2

      - name: Instalacja MicroK8s
        run: |
          sudo snap install microk8s --classic
          sudo microk8s start
          sudo microk8s status --wait-ready
          sudo usermod -aG microk8s runner || true
          sudo chown -R runner /home/runner/.kube || true
          mkdir -p /home/runner/.kube

      - name: Konfiguracja kubeconfig
        run: |
          sudo microk8s kubectl config view --raw > /home/runner/.kube/config
          sudo chown runner /home/runner/.kube/config
          chmod 600 /home/runner/.kube/config

      - name: Instalacja Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Kubernetes Cluster
        run: |
          newgrp microk8s || true
          microk8s kubectl cluster-info

      - name: Helm
        run: |
          newgrp microk8s || true
          helm upgrade --install gitea-environment ./gitea-environment

