name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzanie kodu
        uses: actions/checkout@v2

      - name: Instalacja MicroK8s
        run: |
          sudo snap install microk8s --classic
          sudo microk8s start
          sudo microk8s status --wait-ready
          sudo usermod -aG microk8s runner
          mkdir -p $HOME/.kube
          sudo chown -R runner $HOME/.kube

      - name: Grupy użytkowników
        run: sudo newgrp microk8s || true

      - name: Konfiguracja kubeconfig
        run: |
          sudo microk8s kubectl config view --raw > $HOME/.kube/config
          chmod 777 $HOME/.kube/config

      - name: Instalacja Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Kubernetes Cluster
        run: |
          sudo newgrp microk8s || true
          sudo microk8s kubectl cluster-info

      - name: Helm
        run: |
          newgrp microk8s || true
          sudo helm upgrade --install gitea-environment ./gitea-environment

      - name: Usunięcie losowego poda
        run: |
          echo "Usuwanie losowego poda..."
          pod_name=$(sudo microk8s kubectl get pods -l app=gitea -o jsonpath='{.items[0].metadata.name}')
          echo "Usuwam pod: $pod_name"
          sudo microk8s kubectl delete pod $pod_name
          echo "Usunięty pod: $pod_name"

      - name: Sprawdzenie stanu zdrowia podów
        run: |
          set -e
          echo "Sprawdzanie podów..."
          for pod in whoami grafana gitea prometheus; do
            echo "Sprawdzam pod: $pod"
            status=$(sudo microk8s kubectl get pod -l app=$pod -o jsonpath='{.items[0].status.containerStatuses[0].ready}')
            if [ "$status" != "true" ]; then
              echo "Pod $pod nie jest gotowy!"
              exit 1
            fi
          done
          echo "Wszystkie pody dzialaja"

