name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Tworzy katalog .kube, jeśli nie istnieje
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Print Kubeconfig
        run: |
          cat $HOME/.kube/config  # Wyświetla zawartość pliku Kubeconfig

      - name: Deploy with Helm
        run: |
          helm upgrade --install gitea-environment ./gitea-environment

