name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzanie kodu
        uses: actions/checkout@v2

      - name: Instalacja MicroK8s
        run: |
          sudo snap install microk8s --classic
          sudo microk8s start
          sudo microk8s status --wait-ready
          sudo usermod -a -G microk8s runner
          sudo chown -R runner ~/.kube
          newgrp microk8s || true # aktualizacja grupy

      - name: Utworzenie .kube
        run: mkdir -p $HOME/.kube

      - name: Konfiguracja kubeconfig
        run: |
          sudo microk8s kubectl config view --raw > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Instalacja Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Kubernetes Cluster
        run: |
          microk8s kubectl cluster-info

      - name: Helm
        run: |
          helm upgrade --install gitea-environment ./gitea-environment

