name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzanie kodu
        uses: actions/checkout@v2

      - name: Install MicroK8s
        uses: balchua/microk8s-actions@v0.4.0
        with:
          channel: '1.30/stable'
          addons: '["dns", "rbac", "hostpath-storage", "registry", "metrics-server", "ingress", "storage", "dashboard", "prometheus"]'

      - name: Instalacja Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Kubernetes Cluster
        run: |
          sudo newgrp microk8s || true
          sudo microk8s kubectl cluster-info

      - name: Helm
        run: |
          newgrp microk8s || true
          helm upgrade --install gitea-environment ./gitea-environment
          
      - name: Tworzenie podów z deployment.yaml
        run: |
          if [ -f deployment.yaml ]; then
              sudo microk8s kubectl apply -f deployment.yaml
              echo "Pody zostały utworzone na podstawie deployment.yaml."
          else
              echo "Nie znaleziono pliku deployment.yaml."
          fi
      
   
      - name: Sprawdzam stan deploymentów
        run: |
          echo "Sprawdzam stan deploymentów..."
          DEPLOY_STATUS=$(sudo microk8s kubectl get deployments --field-selector=status.availableReplicas!=1 --no-headers | wc -l)
          if [ $DEPLOY_STATUS -eq 0 ]; then
              echo "Wszystkie deploymenty mają dostępne repliki. Przechodzę do testów."
          else
              echo "Niektóre deploymenty nie mają dostępnych replik. Zatrzymuję pipeline."
              sudo microk8s kubectl get deployments
              exit 1
          fi
