name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sprawdzanie kodu
        uses: actions/checkout@v2

      - name: Install MicroK8s
        uses: balchua/microk8s-actions@v0.4.0
        with:
          channel: '1.30/stable'
          addons: '["dns", "rbac", "hostpath-storage", "registry", "metrics-server", "ingress", "storage", "dashboard", "prometheus"]'

      - name: Instalacja Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Kubernetes Cluster
        run: |
          sudo newgrp microk8s || true
          sudo microk8s kubectl cluster-info

      - name: Helm
        run: |
          newgrp microk8s || true
          helm upgrade --install gitea-environment ./gitea-environment

      - name: Usunięcie losowego poda
        run: |
          echo "Usuwam losowy pod z Helm chartów..."
          pod_name=$(sudo microk8s kubectl get pods -l app=gitea -o jsonpath='{.items[0].metadata.name}' || echo "")
          if [ -z "$pod_name" ]; then
            echo "Nie znaleziono żadnych podów do usunięcia!"
            exit 1
          fi
          echo "Usuwam pod: $pod_name"
          sudo microk8s kubectl delete pod $pod_name
          echo "Usunięto pod: $pod_name"


      - name: Sprawdzenie stanu zdrowia podów
        run: |
          set -e
          echo "Sprawdzanie zdrowia podów..."
          for pod in whoami grafana gitea prometheus; do
            echo "Sprawdzam pod: $pod"
            status=$(sudo microk8s kubectl get pod -l app=$pod -o jsonpath='{.items[0].status.containerStatuses[0].ready}')
            if [ "$status" != "true" ]; then
              echo "Pod $pod nie jest gotowy!"
              exit 1
            fi
          done
          echo "Wszystkie pody są zdrowe!"
