name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MicroK8s
        run: |
          sudo snap install microk8s --classic
          sudo microk8s start
          sudo microk8s kubectl config view --raw > $HOME/.kube/config

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Check Kubernetes Cluster
        run: |
          microk8s kubectl cluster-info

      - name: Deploy with Helm
        run: |
          helm upgrade --install gitea-environment ./gitea-environment

