name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Utwórz katalog, jeśli nie istnieje
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Port Forwarding
        run: |
          nohup kubectl port-forward service/whoami 8080:80 &
          sleep 5  # Daj czas na uruchomienie port forward

      - name: Deploy with Helm
        run: |
          helm upgrade --install gitea-environment ./gitea-environment

