name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Kubernetes
      uses: manusa/actions-setup-minikube@v2.4.1
      with:
        minikube version: 'v1.23.0'
    - name: Deploy with Helm
      run: |
        helm upgrade --install whoami ./whoami-chart
    - name: Test Deployment
      run: |
        kubectl get pods
        kubectl get services
