name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v3


    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.24.0'


    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config


    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash


    - name: Install MicroK8s
      run: |
        sudo snap install microk8s --classic
        sudo microk8s status --wait-ready
        sudo microk8s enable dns storage ingress


    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/deployment.yaml
        helm upgrade --install your-release ./charts/your-chart --namespace default


    - name: Wait for Pods to be Ready
      run: |
        sudo microk8s kubectl wait --for=condition=ready pod -l app=whoami --timeout=120s


    - name: Test Whoami Application
      run: |
        SERVICE_IP=$(sudo microk8s kubectl get service whoami-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://$SERVICE_IP)
        if [ "$STATUS_CODE" != "200" ]; then
          echo "Test failed, expected HTTP 200, got $STATUS_CODE"
          exit 1
        else
          echo "Test passed with HTTP 200"
        fi

